name: CI

on:
  push:
    branches: [ "main", "api_security", "Conteneur-Flavien", "patricia"]
  pull_request:
    branches: [ "main", "api_security", "Conteneur-Flavien", "patricia"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install fastapi[all]
        pip install pytest

    - name: Run tests
      run: |
        pytest


